# Generated by Django 4.1.7 on 2023-04-01 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория платежа',
                'verbose_name_plural': 'Категории платежа',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Способ платежа',
                'verbose_name_plural': 'Способы платежа',
            },
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип транзакции',
                'verbose_name_plural': 'Типы транзакции',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время')),
                ('amount', models.FloatField(help_text='В рублях', verbose_name='Сумма платежа')),
                ('client_fee', models.FloatField(default=0, verbose_name='Комиссия клиента')),
                ('payout_fee', models.FloatField(default=0, verbose_name='Комиссия за выплату')),
                ('interchange_fee', models.FloatField(default=0, verbose_name='Плата за обмен')),
                ('pay_system_fee', models.FloatField(default=0, verbose_name='Системная комиссия')),
                ('paying_fee', models.FloatField(default=0, verbose_name='Пошлина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorytransaction', verbose_name='Категория платежа')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmethodtransaction', verbose_name='Способ платежа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Пользователь')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typetransaction', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Гендер',
                'verbose_name_plural': 'Гендер',
            },
        ),
    ]
