# Generated by Django 4.1.7 on 2023-04-01 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transactions_options_remove_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата регистрации')),
                ('deletion_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата удаления')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платежная карта',
                'verbose_name_plural': 'Платежные карта',
            },
        ),
    ]
