# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Платежная карта', 'verbose_name_plural': 'Платежные карты'},
        ),
        migrations.AlterField(
            model_name='card',
            name='deletion_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='card',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата регистрации'),
        ),
    ]
